language: node_js
node_js:
  - '6'
before_install:
  - npm install -g grunt-cli
install:
  - npm install
before_script:
  - php src/lib/pre-install.php --skip-download --non-interactive
script:
  - grunt builddist