language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - nvm install v0.8.0
  - nvm use v0.8.0
  - npm install -g grunt-cli
  - npm --version
  - node --version
install:
  - npm install
before_script:
  - php src/lib/pre-install.php